### ISSUE TITLE
AWS lex web ui voice not working in chrome and edge

### ISSUE THREAD

**Issue by apoorvanand** [aws-samples/aws-lex-web-ui#153]
I tried the example aws lex webui cloudformation stack available at https://aws.amazon.com/blogs/machine-learning/deploy-a-web-ui-for-your-chatbot/ ,After deploying this stack ,I am unable to interact with voice in chrome and in edge it stops at fulfilment with error message as too many consecutive silent recordings.
Please find the logs for the same.
In Chrome :
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:8436 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
LexWeb.vue:312 running in standalone mode
recorder.js:433 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
_initAudioContext @ recorder.js:433
init @ recorder.js:266
initRecorder @ actions.js:118
wrappedActionHandler @ vuex.js:710
dispatch @ vuex.js:432
boundDispatch @ vuex.js:338
(anonymous) @ LexWeb.vue:116
Promise.then (async)
created @ LexWeb.vue:111
callHook @ vue.js:2895
Vue._init @ vue.js:4547
VueComponent @ vue.js:4715
createComponentInstanceForVnode @ vue.js:4236
init @ vue.js:4053
createComponent @ vue.js:5499
createElm @ vue.js:5447
patch @ vue.js:5982
Vue._update @ vue.js:2637
updateComponent @ vue.js:2765
get @ vue.js:3113
Watcher @ vue.js:3102
mountComponent @ vue.js:2772
Vue$3.$mount @ vue.js:8416
Vue$3.$mount @ vue.js:10777
init @ vue.js:4059
createComponent @ vue.js:5499
createElm @ vue.js:5447
updateChildren @ vue.js:5736
patchVnode @ vue.js:5827
patch @ vue.js:5987
Vue._update @ vue.js:2647
updateComponent @ vue.js:2765
get @ vue.js:3113
run @ vue.js:3190
flushSchedulerQueue @ vue.js:2954
(anonymous) @ vue.js:1815
flushCallbacks @ vue.js:1736
Promise.then (async)
microTimerFunc @ vue.js:1784
nextTick @ vue.js:1828
queueWatcher @ vue.js:3041
update @ vue.js:3180
Vue.$forceUpdate @ vue.js:2668
forceRender @ vue.js:2292
(anonymous) @ vue.js:2302
(anonymous) @ vue.js:318
Promise.then (async)
resolveAsyncComponent @ vue.js:2326
createComponent @ vue.js:4145
_createElement @ vue.js:4357
createElement @ vue.js:4294
vm._c @ vue.js:4410
(anonymous) @ VM928:3
Vue._render @ vue.js:4465
updateComponent @ vue.js:2765
get @ vue.js:3113
Watcher @ vue.js:3102
mountComponent @ vue.js:2772
Vue$3.$mount @ vue.js:8416
Vue$3.$mount @ vue.js:10777
(anonymous) @ fullpage-component-loader.js:366
F @ _export.js:35
mountComponent @ fullpage-component-loader.js:348
(anonymous) @ fullpage-component-loader.js:304
Promise.then (async)
(anonymous) @ fullpage-component-loader.js:302
Promise.then (async)
load @ fullpage-component-loader.js:296
(anonymous) @ index.js:95
Promise.then (async)
load @ index.js:94
load @ index.js:127
(anonymous) @ index.html:68
actions.js:171 recorder content types: audio/wav
recorder.js:524 using media stream track labeled:  Default - Microphone Array (Realtek Audio)
LexWeb.vue:136 sucessfully initialized lex web ui version:  0.14.6

In Edge 
[object Error]: {description: "Too many consecutive silent recordings: 3.", message: "Too many consecutive silent recordings: 3.", stack: "Error: Too many consecutive silent recordings: 3. at Anonymous function (https://lex-web-ui-codebuilddeploy-t6bk5y86j-webappbucket-5tkhrr2hpp2x.s3.amazonaws.com/lex-web-ui.js:35551:9) at run (https://lex-web-ui-codebuilddeploy-t6bk5y86j-webappbucket-5tkhrr2hpp2x.s3.amazonaws.com/lex-web-ui.js:17582:13) at Anonymous function (https://lex-web-ui-codebuilddeploy-t6bk5y86j-webappbucket-5tkhrr2hpp2x.s3.amazonaws.com/lex-web-ui.js:17595:30) at flush (https://lex-web-ui-codebuilddeploy-t6bk5y86j-webappbucket-5tkhrr2hpp2x.s3.amazonaws.com/lex-web-ui.js:17877:9)"}

**Comment by bobpskier** [comment]
I'm working on a fix for Chrome. Reordering of AudioContext initialization is required based on changes made to Chrome.

**Comment by apoorvanand** [comment]
I want to display a table as a response in  the fulfilment request , can u help me out on this as well @bobpskier . For example , if I am creating a pizza ordering bot , i want to show the types of pizza and its price as per user choice ,As far as I know , lex doesnot support html tags in response, any idea how to implement this.

**Comment by bobpskier** [comment]
I just committed a fix on the development branch for the audio context issue on Chrome. I've not tried on Edge but will give this a test shortly. If you have the ability to rebuild and redeploy using the development branch, could you give this a try? If not I'll get this pushed to master branch soon. 

For tables, take a look at https://github.com/aws-samples/aws-lex-web-ui/issues/130. This provides an example of returning markdown with the lex response which the lex-web-ui will format correctly.

**Comment by apoorvanand** [comment]
I am still facing the same issue@bobpskier , can you please merge this with master and update in the auto deploy cloud formation script artifacts as well.

**Comment by bobpskier** [comment]
@apoorvanand  - Released version 0.14.7 that should fix the Chrome AudioContext initialization issue. It is available in the standard bootstrap bucket which is used when clicking on Launch Stack in the blog post at https://www.amazon.com/chatbotui. Please let me know if this resolves your issue.

**Comment by apoorvanand** [comment]
@bobpskier  for chrome its working now , and for the markdown in lambda function where I need to send in fulfilment state , I tried adding this object after messages but it was failing {
    "appContext":{
        "altMessages":{
            "markdown":"# hello!"
        }
    }
}

**Comment by bobpskier** [comment]
Make sure to set ui.AllowSuperDangerousHTMLInMessage in config to be true to allow markdown and also html to be processed by the ui. See [Markdown and HTML Support](https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#markdown-and-html-support) in the lex web ui readme.

**Comment by apoorvanand** [comment]
It is there in my ui config.json ` "lex": {
    "botName": "SkillSetBot",
    "botAlias": "$LATEST",
    "initialText": "You can ask me for help finding Skilled resources. Just type \"Show me resources\" or click on the mic and say it.",
    "initialSpeechInstruction": "Say 'Show me resources' to get started.",
    "reInitSessionAttributesOnRestart": false
  },
  "ui": {
    "parentOrigin": "https://skillbot-codebuilddeploy-2srama7aoym-webappbucket-m98y0zwmvs2i.s3.amazonaws.com",
    "toolbarTitle": "SkillBot",
    "toolbarLogo": "",
    "enableLogin": true,
    "AllowSuperDangerousHTMLInMessage": true,
    "shouldDisplayResponseCardTitle": true,
    "pushInitialTextOnRestart": false,
    "directFocusToBotInput": false
  },
  "polly": {
    "voiceId": "Salli"
  },
  "recorder": {
    "preset": "speech_recognition"
  },
  "iframe": {
    "iframeOrigin": "https://skillbot-codebuilddeploy-2srama7aoym-webappbucket-m98y0zwmvs2i.s3.amazonaws.com",
    "shouldLoadIframeMinimized": false,
    "iframeSrcPath": "/index.html#/?lexWebUiEmbed=true"
  }
}`
@bobpskier Can u share any sample message json object with html tags complete message object
